FROM ubuntu:22.04

RUN sed -i 's/\/\/archive\.ubuntu\.com/\/\/hk\.archive\.ubuntu\.com/g' /etc/apt/sources.list && \
  sed -i 's/\/\/security\.ubuntu\.com/\/\/hk\.archive\.ubuntu\.com/g' /etc/apt/sources.list

RUN apt update 
