version: "3.4"

services:
  app:
    image: monica:apache
    container_name: MonicaHQ
    depends_on:
      - db
    networks:
      - default
    ports:
      - 8083:80
    environment:
      - APP_KEY=xlhF31NeOlibJcoOW9tvZg7TkHcAZI3a
      - DB_HOST=db
      - DB_USERNAME=usermonica
      - DB_PASSWORD=secret
    # volumes:
      # - ./data:/var/www/html/storage
    restart: always

  db:
    image: mysql
    container_name: Monica-DB
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=usermonica
      - MYSQL_PASSWORD=secret
    # volumes:
      # - mysql:/var/lib/mysql
    restart: always

volumes:
  mysql:
    name: mysql
