services:
  n8n:
    image: n8nio/n8n
    restart: unless-stopped
    ports:
      - 5678:5678
    volumes:
      - ./volumes/.n8n:/home/node/.n8n
    # Wait 5 seconds to start n8n to make sure that PostgreSQL is ready
    # when n8n tries to connect to it
    command: /bin/sh -c "sleep 5; n8n start"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n-http.rule=Host(`n8n.iamon99.com`)"
      - "traefik.http.routers.n8n-http.entrypoints=web"
      - "traefik.http.routers.n8n-http.middlewares=n8n-https"
      
      - "traefik.http.middlewares.n8n-https.redirectscheme.scheme=https"
      - "traefik.http.routers.n8n.rule=Host(`n8n.iamon99.com`)"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.tls.certresolver=myresolver"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"

networks:
  default:
    name: traefik-proxy-network
    external: true
