# https://docs.n8n.io/hosting/installation/server-setups/docker-compose/#5-create-docker-compose-file

services:
  n8n:
    image: n8nio/n8n
    restart: unless-stopped
    ports:
      - 5678:5678

    # Wait 5 seconds to start n8n to make sure that PostgreSQL is ready
    # when n8n tries to connect to it
    command: /bin/sh -c "sleep 5; n8n start"

    labels:
      # TODO: 2023-Jul-12, remove me as no encrypted traffic between cloudflare and my server anymore.
      # - traefik.enable=true
      # - traefik.http.routers.n8n.rule=Host(`${SUBDOMAIN}.${DOMAIN_NAME}`)
      # - traefik.http.routers.n8n.tls=true
      # - traefik.http.routers.n8n.entrypoints=web,websecure
      # - traefik.http.routers.n8n.tls.certresolver=mytlschallenge
      # - traefik.http.middlewares.n8n.headers.SSLRedirect=true
      # - traefik.http.middlewares.n8n.headers.STSSeconds=315360000
      # - traefik.http.middlewares.n8n.headers.browserXSSFilter=true
      # - traefik.http.middlewares.n8n.headers.contentTypeNosniff=true
      # - traefik.http.middlewares.n8n.headers.forceSTSHeader=true
      # - traefik.http.middlewares.n8n.headers.SSLHost=${DOMAIN_NAME}
      # - traefik.http.middlewares.n8n.headers.STSIncludeSubdomains=true
      # - traefik.http.middlewares.n8n.headers.STSPreload=true
      # - traefik.http.routers.n8n.middlewares=n8n@docker

      - "traefik.enable=true"
      - "traefik.http.routers.n8n-iamon99.rule=Host(`n8n.iamon99.com`)"
      - "traefik.http.routers.n8n-iamon99.entrypoints=web"
      - "traefik.http.services.n8n-iamon99.loadbalancer.server.port=5678"

    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER
      - N8N_BASIC_AUTH_PASSWORD
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}

    volumes:
      - ./volumes/.n8n:/home/node/.n8n
      - ./volumes/n8n-local-files:/files
