services:
  mongo:
    image: bitnami/mongodb:latest
    # container_name: db
    # restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/mongo:/data/db

  mongo-express:
    image: mongo-express:latest
    # container_name: db_gui
    # restart: unless-stopped
    # depends_on:
      # - mongo
    ports:
      - "8081:8081"
    volumes:
      - ./volumes/mongo-express:/app
      - ./volumes/mongo-express/docker-entrypoint.sh:/docker-entrypoint.sh
    links:
        - mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=user
      - ME_CONFIG_BASICAUTH_PASSWORD=password
      # - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance

volumes:
  db_data:
