services:
  cloudflare-companion:
    image: tiredofit/traefik-cloudflare-companion
    restart: unless-stopped

    volumes:
      - ${SOCK_PATH:-/var/run/docker.sock}:/var/run/docker.sock

    environment:
      - TRAEFIK_VERSION=2
      - LOG_TYPE=BOTH
      - LOG_LEVEL=INFO
      
    dns: 1.1.1.1
    env_file: ./.env
