# not tested
version: "2"
services:
  cloudflare-companion:
    image: tiredofit/traefik-cloudflare-companion
    container_name: cloudflare-companion
    restart: unless-stopped
    volumes:
      - ${SOCK_PATH:-/var/run/docker.sock}:/var/run/docker.sock
    environment:
      - "TRAEFIK_VERSION=2"
      # - "CF_EMAIL=" Leave blank for scopepd
      - "CF_TOKEN=${CF_TOKEN}"
      - "TARGET_DOMAIN=${SUBDOMAIN}.${DNS_DOMAIN}"
      - "DOMAIN1=${DNS_DOMAIN}"
      - "DOMAIN1_ZONE_ID=${DNS_DOMAIN_ZONE_ID}"
    dns: 1.1.1.1
