FROM ubuntu:latest

ENV DEBIAN_FRONTEND noninteractive

RUN apt update &&\
    apt install  openssh-server sudo -y &&\
    apt install openjdk-8-jdk -y &&\
    apt install git wget curl -y

RUN useradd -rm -d /home/jenkins -s /bin/bash -g root -G sudo -u 1000 jenkins 

RUN  echo 'jenkins:jenkins' | chpasswd

RUN service ssh start

EXPOSE 22

# build specific tools starts here

RUN curl -sL https://deb.nodesource.com/setup_14.x | sudo bash - 
RUN apt -y install nodejs
RUN node  -v

RUN apt -y install gcc g++ make

RUN curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
RUN apt update && sudo apt install yarn
RUN yarn -V

RUN apt install -y python python3 python3-pip pipenv

RUN mkdir -p /home/jenkins/.ssh
COPY ./home/jenkins/.ssh /home/jenkins/.ssh
RUN chown jenkins:root -R /home/jenkins/.ssh

CMD ["/usr/sbin/sshd","-D"]

