# https://docs.travis-ci.com/user/conditional-builds-stages-jobs/
# https://docs.travis-ci.com/user/conditions-v1
stages:
  - name: Build_docker

  - name: Unit_test
  - name: Test
  - name: Build
  - name: Deploy

  - name: Integration_to_other_repo
    if: branch = develop

  - name: Test_publish_dashboard
    if: branch = develop

  - name: Publish_dashboard
    if: branch = master

  - name: Test_cron

  - name: Merge

  - name: Cron
    if: type = cron
