services:
  registry:
    image: registry:2
    container_name: docker-registry
    restart: unless-stopped
    # environment:
    #   REGISTRY_AUTH: htpasswd
    #   REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    #   REGISTRY_AUTH_HTPASSWD_REALM: Local Registry Realm
    ports:
      - 5000:5000
    volumes:
      - /mnt/sda/_docker/volumes/registry/data:/var/lib/registry
      # - ./auth:/auth:ro
