services:
  minio:
    image: minio/minio:latest
    restart: unless-stopped
    environment:
      MINIO_BROWSER: on
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - /mnt/sdb1/docker_volumes/minio/data:/data
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
