FROM ubuntu:18.04

# Set default user and workdir
USER root
WORKDIR /

# Set DEBIAN_FRONTEND to noninteractive
ENV DEBIAN_FRONTEND noninteractive

RUN sed -i 's/http:\/\/archive\.ubuntu\.com/http:\/\/ftp\.cuhk\.edu\.hk\/pub\/Linux/g' /etc/apt/sources.list && \
  sed -i 's/http:\/\/security\.ubuntu\.com/http:\/\/ftp\.cuhk\.edu\.hk\/pub\/Linux/g' /etc/apt/sources.list

RUN apt-get update && \
  apt-get install -qqy zsh sudo

RUN apt-get install -qqy curl
RUN apt-get install -qqy python3 python3-pip

# sudo apt-get install -qqy npm

CMD ["/bin/bash"]
