version: "3.4"

services:
  db:
    image: mysql
    # container_name: Monica-DB
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=usermonica
      - MYSQL_PASSWORD=secret
    # volumes:
      # - mysql:/var/lib/mysql
    restart: always
