version: "3.4"

services:
  db:
    image: mysql
    # container_name: Monica-DB
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=usermonica
      - MYSQL_PASSWORD=secret
    # volumes:
    # - mysql:/var/lib/mysql
    restart: always

  whoami:
    image: "traefik/whoami"
    # container_name: "whoami_root"
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.whoami_root.rule=Host(`whoami_react_test.iamon99.com`)"
    #   - "traefik.http.routers.whoami_root.entrypoints=websecure"
    #   - "traefik.http.routers.whoami_root.tls.certresolver=myresolver"
    restart: always
