# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
# https://github.com/sdras/awesome-actions

docker_gnome_tryout:
  runs-on: ubuntu-latest
  steps:
    - name: docker-gnome-tryout
      uses: actions/checkout@v2

    - name: try build image
      env: # Or as an environment variable
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      run: |
        cd docker-gnome-tryout
          docker build -t logickee/ubuntu_gnome -f dockerfile .
        cd ..
