# FROM ubuntu:latest
FROM ubuntudesktop/gnome-3-28-1804

# Set default user and workdir
USER root
WORKDIR /

# Set DEBIAN_FRONTEND to noninteractive
ENV DEBIAN_FRONTEND noninteractive

RUN sed -i 's/http:\/\/archive\.ubuntu\.com/http:\/\/ftp\.cuhk\.edu\.hk\/pub\/Linux/g' /etc/apt/sources.list && \
  sed -i 's/http:\/\/security\.ubuntu\.com/http:\/\/ftp\.cuhk\.edu\.hk\/pub\/Linux/g' /etc/apt/sources.list


RUN apt-get update && \
  apt-get install -y zsh sudo

# Run zsh
CMD ["/bin/zsh"]
