# CREDIT: https://github.com/shepherdjerred/servers/blob/main/zeus/docker-compose.yml

services:
  apprise:
    image: lscr.io/linuxserver/apprise-api
    restart: always
    ports:
      - 8000:8000
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Hong_Kong
      - VERSION=docker
    volumes:
      - "./volumes/config/:/config"

networks:
  default:
    external:
      name: traefik-proxy-network
