version: "3"
services:
  # admin@123.com
  # Aa1234567

  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    links:
      - postgres:postgres
    volumes:
      - ./volume/strapi/app:/srv/app
    ports:
      - "1337:1337"
    depends_on:
      - postgres
    networks:
      - strapi-hooby-dev_postgres-network

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./volume/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - strapi-hooby-dev_postgres-network

  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports:
      - "8084:8081"
    links:
      - postgres:postgres
    environment:
      - DATABASE_URL=postgres://strapi:strapi@postgres:5432/strapi?sslmode=disable
    depends_on:
      - postgres
    networks:
      - strapi-hooby-dev_postgres-network

networks:
  strapi-hooby-dev_postgres-network:
    driver: bridge
