services:
  static_html_tryout:
    build: .
    restart: always
    volumes:
      - ./app:/app
      - static_node_modules:/app/node_modules
    working_dir: /app
    # command: sleep infinity
    command: bash entry.sh

    ports:
      - 8080

volumes:
  static_node_modules:
