version: "3.9"

services:
  mautic:
    image: mautic/mautic:v4
    ports:
      - 8082:80
    environment:
      MAUTIC_DB_HOST: mysql
      MAUTIC_DB_USER: root
      MAUTIC_DB_PASSWORD: password
      MAUTIC_DB_NAME: mautic
      MAUTIC_RUN_CRON_JOBS: "true"
    depends_on:
      - mysql
    # restart: always
  mysql:
    image: mysql:8.0.29
    command: |
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --sql-mode=""
    environment:
      MYSQL_DATABASE: tests
      MYSQL_USER: gabrielrufino
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./volumes/mysql/:/home/shared
      - ./volumes/mysql:/var/lib/mysql
    # restart: always
