version: "3.5"

services:
  postgres:
    image: "postgres:13.1-alpine"
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=database
      - PGDATA=/data/postgres
    ports:
      - "5051:5432"
    volumes:
      - ./volumes/postgres:/data/postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - ./volumes/pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
