version: "3"

services:
  postgres:
    image: postgres
    # container_name: postgres_container
    hostname: "pgserver"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/postgres:/data/postgres
    ports:
      - "5432:5432"
    # networks:
    #   - postgres
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    # container_name: pgadmin_container
    hostname: "pgadmin"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@123.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/pgadmin:/var/lib/pgadmin
      - ./volumes/pgadmin/sessions:/var/lib/pgadmin/sessions
      - ./volumes/pgadmin/storage:/var/lib/pgadmin/storage

    depends_on:
      - postgres
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    # networks:
    #   - postgres
    restart: unless-stopped
