version: "3"

services:
  express:
    build: ./express
    ports:
      - "3000:3000"
    # environment:
    #   - API_PORT=3000
    #   - NODE_ENV=development
    #   - DATABASE_URL=mongodb://mongodb:27017/myapp
    #   - EXPRESS_SKIP_DB_WAIT=0
    #   - EXPRESS_SKIP_DB_MIGRATION=0
    #   - EXPRESS_SKIP_NPM_INSTALL=0
    #   - EXPRESS_SKIP_BOWER_INSTALL=0
    volumes:
      - "./express:/app"
    command: "npm run development"
