version: '3.7'

services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.3
    # Run as 'root' instead of 'filebeat' (uid 1000) to allow reading
    # 'docker.sock' and the host's filesystem.
    user: root
    command:
      # Log to stderr.
      - -e
      # Disable config file permissions checks. Allows mounting
      # 'config/filebeat.yml' even if it's not owned by root.
      # see: https://www.elastic.co/guide/en/beats/libbeat/7.17/config-file-permissions.html
      - --strict.perms=false
    volumes:
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro,Z
      - type: bind
        source: /var/lib/docker/containers
        target: /var/lib/docker/containers
        # snap install docker
        # source: /var/snap/docker/common/var-lib-docker/containers
        # target: /var/snap/docker/common/var-lib-docker/containers
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      # - type: bind
      #   source: YOUR_NGINX_LOG/nginx_log/
      #   target: /usr/share/filebeat/nginx/
      #   read_only: true
    environment:
      ELASTIC_PASSWORD: changeme
    # networks:
    #   - elk
    # depends_on:
    #   - elasticsearch
