services:
  test:
    # image: ubuntu:latest
    build: .
    restart: unless-stopped
    environment:
      - CRON_DB_PATH=/home/crontab-ui/data
      - BASIC_AUTH_USER=${CONFIG_USER_NAME}
      - BASIC_AUTH_PWD=${CONFIG_USER_PASS}
      - HOST=0.0.0.0
      - PORT=8000
    ports:
      - 18889:8000
    volumes:
      # - ./volumes/crontab-ui:/home/crontab-ui
      - ./volumes/crontab-ui/data:/home/crontab-ui/data
      - ./volumes/crontab-ui/data/logs:/home/crontab-ui/data/logs
      - ${PWD}:/home/crontab-ui
    working_dir: /home/crontab-ui
    env_file: ./.env
    command: "bash -c crontab-ui"
    # command: sleep infinity
