services:
  cloudflare-louislabs:
    image: oznu/cloudflare-ddns:latest
    restart: unless-stopped
    labels:
      - traefik.enable=false
    env_file: ./.louislabs.env

  cloudflare-iamon99:
    image: oznu/cloudflare-ddns:latest
    restart: unless-stopped
    labels:
      - traefik.enable=false
    env_file: ./.iamon99.env
