services:
  mongo:
    image: bitnami/mongodb:latest
    # container_name: db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongo/db_data:/data/db

  mongoGUI:
    image: mongo-express:latest
    # container_name: db_gui
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - 8081:8081
    volumes:
      - ./volumes/mongoGUI/db_data:/data/db
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=user
      - ME_CONFIG_BASICAUTH_PASSWORD=password

volumes:
  db_data:
