version: '3.3'
services:
    cli:
        image: dockersf/letsencrypt-manager:latest
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
            - /var/lib/letsencrypt:/var/lib/letsencrypt
            - /var/acme-webroot:/var/acme-webroot
            - ./cli.ini:/root/.config/letsencrypt/cli.ini

    cron:
        image: dockersf/letsencrypt-manager:latest
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
            - /var/lib/letsencrypt:/var/lib/letsencrypt
            - /var/acme-webroot:/var/acme-webroot
            - ./cli.ini:/root/.config/letsencrypt/cli.ini
        command: cron-auto-renewal
        restart: always

    nginx:
        image: bringnow/nginx-letsencrypt
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites_conf:/etc/nginx/sites_conf
            - /etc/letsencrypt:/etc/letsencrypt
            - /var/acme-webroot:/var/acme-webroot
            - ./nginx/dhparam:/etc/nginx/dhparam
        ports:
            - "80:80"
            - "443:443"
        # net: "host"
        dns_search:
            - "louislabs.com"

    helloworld:
        image: tutum/hello-world
        container_name: hello_louislabs_com
        ports:
            - "8001:80"
