FROM ubuntu:18.04

# Set DEBIAN_FRONTEND to noninteractive
ENV DEBIAN_FRONTEND noninteractive

RUN sed -i 's/http:\/\/archive\.ubuntu\.com/http:\/\/ftp\.cuhk\.edu\.hk\/pub\/Linux/g' /etc/apt/sources.list && \
  sed -i 's/http:\/\/security\.ubuntu\.com/http:\/\/ftp\.cuhk\.edu\.hk\/pub\/Linux/g' /etc/apt/sources.list

# Set default user and workdir
USER root
WORKDIR /

RUN apt-get update && \
  apt-get install -y zsh sudo curl gnupg2

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt-get -qqy install nodejs

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
  echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
  apt-get update && \
  apt-get install -qqy yarn

RUN yarn global add puppeteer && yarn cache clean

CMD ["/bin/bash"]
