#CREDIT: https://github.com/dorahero/proxy_pool_api/blob/7f2ebb975e05e30e3fe3edb8ba326734deda4e25/docker-compose.yml

version: "3"

services:
  proxy-scylla:
    image: wildcat/scylla:1.1.7
    # container_name: proxy-scylla
    restart: always
    ports:
      - 8899:8899
      - 8081:8081
    volumes:
      - ./volumes/scylla:/var/www/scylla
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "Asia/Hong_Kong"
      VERSION: "docker"
# networks:
#   default:
#     external:
#       name: traefik-proxy-network
