version: "2.1"

# CREDIT: https://github.com/louislam/uptime-kuma
services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    environment:
      TZ: ${CONFIG_SYSTEM_REGION}
      UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN: 1
    volumes:
      - "./volumes/etc-uptimekuma/:/app/data"
    ports:
      - 50102:3001
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime_kuma.rule=Host(`status.iamon99.com`)"
      - "traefik.http.routers.uptime_kuma.entrypoints=websecure"
      - "traefik.http.routers.uptime_kuma.tls.certresolver=myresolver"
      - "traefik.http.services.uptime_kuma.loadbalancer.server.port=3001"

networks:
  default:
    external:
      name: traefik-proxy-network
