# CREDIT: https://github.com/louislam/uptime-kuma
services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    environment:
      TZ: "Asia/Hong_Kong"
      UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN: 1
    volumes:
      - "./volumes/app/data:/app/data"
      # - /etc/localtime:/etc/localtime:ro
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped
    labels:
      # # TODO: 2023-Jul-12, remove me as no encrypted traffic between cloudflare and my server anymore.
      # - "traefik.enable=true"
      # - "traefik.http.routers.uptime_kuma.rule=Host(`status.iamon99.com`)"
      # - "traefik.http.routers.uptime_kuma.entrypoints=websecure"
      # - "traefik.http.routers.uptime_kuma.tls.certresolver=myresolver"
      # - "traefik.http.services.uptime_kuma.loadbalancer.server.port=3001"

      - "traefik.enable=true"

      - "traefik.http.routers.status-iamon99-http.rule=Host(`status.iamon99.com`)"
      - "traefik.http.routers.status-iamon99-http.entrypoints=web"

      # NOTE: container serving 3001 port
      - "traefik.http.services.status-iamon99-http.loadbalancer.server.port=3001"

networks:
  default:
    external:
      name: traefik-proxy-network
