FROM ubuntu:22.04

# Set default user and workdir
USER root
WORKDIR /

# Set DEBIAN_FRONTEND to noninteractive
ENV DEBIAN_FRONTEND noninteractive

# RUN sed -i 's/http:\/\/archive\.ubuntu\.com/http:\/\/ftp\.cuhk\.edu\.hk\/pub\/Linux/g' /etc/apt/sources.list && \
#   sed -i 's/http:\/\/security\.ubuntu\.com/http:\/\/ftp\.cuhk\.edu\.hk\/pub\/Linux/g' /etc/apt/sources.list

RUN apt update && \
  apt install -qy zsh git && \
  apt clean cache

CMD ["/bin/bash"]
