## Custom Dockerfile
FROM consol/debian-xfce-vnc
ENV REFRESHED_AT 2022-10-12

# Switch to root user to install additional software
USER 0

## Install a gedit
# RUN yum install -y gedit \
#     && yum clean all

# RUN wget https://dl.discordapp.net/apps/linux/0.0.4/discord-0.0.4.tar.gz -O /tmp/discord.tar.gz && \
#     cd /tmp/ && \
#     tar xvzf /tmp/discord.tar.gz && \
#     rm /etc/fonts/conf.d/10-scale-bitmap-fonts.conf && \
#     fc-cache -fv

# RUN apt-get update
# RUN apt-get install -y apt-utils
# RUN apt-get install -y dbus-x11
# RUN apt-get install -y dunst
# RUN apt-get install -y hunspell-en-us
# RUN apt-get install -y python3-dbus
# RUN apt-get install -y software-properties-common
# RUN apt-get install -y libx11-xcb1
# RUN apt-get install -y gconf2
# RUN apt-get install -y libgtk2.0-0
# RUN apt-get install -y libxtst6
# RUN apt-get install -y libnss3
# RUN apt-get install -y libasound2
# RUN apt-get install -y wget
    # --no-install-recommends && \
    # apt-get clean && \
    # rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

## switch back to default user
USER 1000
