services:
  dashy:
    container_name: Dashy
    image: lissy93/dashy
    volumes:
      - ./volumes/my-conf.yml:/app/public/conf.yml
    ports:
      - 8099:80
    
    # environment:
    #   - BASE_URL=/my-dashboard

    restart: always
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
