version: "3.9"

services:
  matomo:
    image: matomo:4.10.0
    ports:
      - 8086:80
    environment:
      MATOMO_DATABASE_HOST: mysql
      MATOMO_DATABASE_USERNAME: root
      MATOMO_DATABASE_PASSWORD: password
      MATOMO_DATABASE_DBNAME: matomo_db
    depends_on:
      - mysql
    # restart: always
  mysql:
    image: mysql:8.0.29
    command: |
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --sql-mode=""
    environment:
      MYSQL_DATABASE: tests
      MYSQL_USER: gabrielrufino
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./volumes/mysql/:/home/shared
      - ./volumes/mysql:/var/lib/mysql
    # restart: always
