FROM ubuntu:18.04


# Set DEBIAN_FRONTEND to noninteractive
ENV DEBIAN_FRONTEND noninteractive
RUN ln -fs /usr/share/zoneinfo/Asia/Hong_Kong /etc/localtime

RUN sed -i 's/http:\/\/archive\.ubuntu\.com/http:\/\/ftp\.cuhk\.edu\.hk\/pub\/Linux/g' /etc/apt/sources.list && \
  sed -i 's/http:\/\/security\.ubuntu\.com/http:\/\/ftp\.cuhk\.edu\.hk\/pub\/Linux/g' /etc/apt/sources.list

RUN apt-get update && \
  apt-get install -y zsh sudo

RUN apt-get install -y software-properties-common
RUN apt-get install -y git

# Set default user and workdir
USER root
WORKDIR /root/work_dir

CMD ["/bin/bash"]
