FROM buildkite/puppeteer:latest

ENV DEBIAN_FRONTEND noninteractive
RUN ln -fs /usr/share/zoneinfo/Asia/Hong_Kong /etc/localtime

RUN sed -i 's/http:\/\/archive\.ubuntu\.com/http:\/\/ftp\.cuhk\.edu\.hk\/pub\/Linux/g' /etc/apt/sources.list && \
  sed -i 's/http:\/\/security\.ubuntu\.com/http:\/\/ftp\.cuhk\.edu\.hk\/pub\/Linux/g' /etc/apt/sources.list

RUN apt update && apt install -y git curl wget sudo

RUN yarn global add node-firestore-import-export

WORKDIR /home/logic/_workspace/LynkedKK

COPY wait-for-it.sh /wait-for-it.sh

COPY wait-ready.sh /wait-ready.sh

COPY entry.sh /entry.sh

# ENTRYPOINT ["./entry.sh"]

CMD ['/bin/bash']