version: "2"
services:
  playwright-chrome:
    hostname: playwright-chrome
    image: browserless/chrome
    restart: unless-stopped
    environment:
      - EXIT_ON_HEALTH_FAILURE=true
      - MAX_CONCURRENT_SESSIONS=10
      - DEFAULT_IGNORE_HTTPS_ERRORS=true
      # - DEFAULT_LAUNCH_ARGS=[\"--window-size=1920,10800\"]

  browser-chrome:
    hostname: browser-chrome
    image: selenium/standalone-chrome-debug:3.141.59
    environment:
      - VNC_NO_PASSWORD=1
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=24
    volumes:
      - /dev/shm:/dev/shm
    restart: unless-stopped

  changedetection.io:
    image: ghcr.io/dgtlmoon/changedetection.io
    # container_name: changedetection.io
    hostname: changedetection.io
    volumes:
      - ./volumes/datastore:/datastore

    environment:
      - PORT=5000
      - PUID=1000
      - PGID=1000
      - WEBDRIVER_URL=http://browser-chrome:4444/wd/hub
      - PLAYWRIGHT_DRIVER_URL=ws://playwright-chrome:3000/

    ports:
      - 5000:5000
    restart: unless-stopped
