# https://docs.browserless.io/docs/docker.html#function-incognito-mode

services:
  browser-chrome:
    image: selenium/standalone-chrome-debug:3.141.59
    restart: always
    environment:
      - VNC_NO_PASSWORD=1
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=5080
      - SE_SCREEN_WIDTH=1920
      - SE_SCREEN_HEIGHT=5080
      - SCREEN_DEPTH=24
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=2
    shm_size: 2gb
    volumes:
      - /dev/shm/changedetection-io:/dev/shm
    #ports:
    #  - 4444:4444

  changedetection.io:
    image: ghcr.io/dgtlmoon/changedetection.io
    user: 1000:1000
    volumes:
      - ./volumes/changedetect/datastore:/datastore
    environment:
      - FETCH_WORKERS=2
      - PORT=5000
      - PUID=1000
      - PGID=1000
      - WEBDRIVER_URL=http://browser-chrome:4444/wd/hub
      # - PLAYWRIGHT_DRIVER_URL=ws://playwright-chrome:3000/
    ports:
      - 5000:5000
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.changedetect-http.rule=Host(`changedetect.iamon99.com`)'
      - 'traefik.http.routers.changedetect-http.entrypoints=web'
      - 'traefik.http.routers.changedetect-http.middlewares=changedetect-https'
      - 'traefik.http.middlewares.changedetect-https.redirectscheme.scheme=https'
      - 'traefik.http.routers.changedetect.rule=Host(`changedetect.iamon99.com`)'
      - 'traefik.http.routers.changedetect.entrypoints=websecure'
      - 'traefik.http.routers.changedetect.tls.certresolver=myresolver'
      - 'traefik.http.services.changedetect.loadbalancer.server.port=5000'

networks:
  default:
    external:
      name: traefik-proxy-network
