version: "2"
services:
  changedetection.io:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection.io
    hostname: changedetection.io
    volumes:
      - ./volumes/datastore:/datastore
    environment:
      - PORT=5000
      - PUID=1000
      - PGID=1000
      - WEBDRIVER_URL=http://browser-chrome:4444/wd/hub

    ports:
      - 5000:5000
    restart: unless-stopped

  browser-chrome:
    hostname: browser-chrome
    image: selenium/standalone-chrome-debug:3.141.59
    environment:
      - VNC_NO_PASSWORD=1
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=24
    volumes:
      - ./volumes/shm:/dev/shm
    restart: unless-stopped
