services:
  playwright-chrome:
    image: browserless/chrome
    restart: always
    shm_size: 2gb
    volumes:
      - /dev/shm:/dev/shms
    environment:
      - EXIT_ON_HEALTH_FAILURE=true
      - MAX_CONCURRENT_SESSIONS=2
      - DEFAULT_IGNORE_HTTPS_ERRORS=true
      - ENABLE_CORS=true
      - PREBOOT_CHROME=true
      - KEEP_ALIVE=true
      - ENABLE_API_GET=true
      - DEFAULT_LAUNCH_ARGS=["--window-size=1920,5080"]

  browser-chrome:
    image: selenium/standalone-chrome-debug:3.141.59
    restart: always
    environment:
      - VNC_NO_PASSWORD=1
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=5080
      - SCREEN_DEPTH=24
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=2
    shm_size: 2gb
    volumes:
      - /dev/shm:/dev/shm
    #ports:
    #  - 4444:4444

  changedetection.io:
    image: ghcr.io/dgtlmoon/changedetection.io
    user: 1000:1000
    volumes:
      - ./volumes/changedetect/datastore:/datastore
    environment:
      - FETCH_WORKERS=2
      - PORT=5000
      - PUID=1000
      - PGID=1000
      - WEBDRIVER_URL=http://browser-chrome:4444/wd/hub
      # - PLAYWRIGHT_DRIVER_URL=ws://playwright-chrome:3000/
    ports:
      - 5000:5000
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.changedetect-http.rule=Host(`changedetect.iamon99.com`)'
      - 'traefik.http.routers.changedetect-http.entrypoints=web'
      - 'traefik.http.routers.changedetect-http.middlewares=changedetect-https'
      - 'traefik.http.middlewares.changedetect-https.redirectscheme.scheme=https'
      - 'traefik.http.routers.changedetect.rule=Host(`changedetect.iamon99.com`)'
      - 'traefik.http.routers.changedetect.entrypoints=websecure'
      - 'traefik.http.routers.changedetect.tls.certresolver=myresolver'
      - 'traefik.http.services.changedetect.loadbalancer.server.port=5000'

  private-changedetect:
    image: ghcr.io/dgtlmoon/changedetection.io
    # container_name: changedetection.io
    # hostname: changedetection.io
    user: 1000:1000
    volumes:
      - ./volumes/private-changedetect/datastore:/datastore
    environment:
      - FETCH_WORKERS=2
      - PORT=5000
      - PUID=1000
      - PGID=1000
      - PLAYWRIGHT_DRIVER_URL=ws://playwright-chrome:3000/
    ports:
      - 5001:5000
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.private-changedetect-http.rule=Host(`private-changedetect.iamon99.com`)'
      - 'traefik.http.routers.private-changedetect-http.entrypoints=web'
      - 'traefik.http.routers.private-changedetect-http.middlewares=private-changedetect-https'
      - 'traefik.http.middlewares.private-changedetect-https.redirectscheme.scheme=https'
      - 'traefik.http.routers.private-changedetect.rule=Host(`private-changedetect.iamon99.com`)'
      - 'traefik.http.routers.private-changedetect.entrypoints=websecure'
      - 'traefik.http.routers.private-changedetect.tls.certresolver=myresolver'
      - 'traefik.http.services.private-changedetect.loadbalancer.server.port=5000'

networks:
  default:
    external:
      name: traefik-proxy-network
