# https://docs.browserless.io/docs/docker.html#function-incognito-mode

services:
  debug-browserless-chrome:
    container_name: debug-browserless-chrome
    hostname: debug-browserless-chrome
    image: browserless/chrome
    restart: always
    shm_size: 2gb
    volumes:
      - /dev/shm/debug-browserless-chrome:/dev/shm
    ports:
      - 14999:3000
      
    environment:
      - EXIT_ON_HEALTH_FAILURE=true
      # means how many client can connect to this browserless machine
      - MAX_CONCURRENT_SESSIONS=5
      - MAX_QUEUE_LENGTH=999
      - CONNECTION_TIMEOUT=30000
      - DEFAULT_IGNORE_HTTPS_ERRORS=true
      - ENABLE_CORS=true
      - PREBOOT_CHROME=true
      - KEEP_ALIVE=true
      - ENABLE_API_GET=true
      - DEFAULT_LAUNCH_ARGS=["--window-size=1920,5080"]
      - FUNCTION_ENABLE_INCOGNITO_MODE=true
      - METRICS_JSON_PATH=/root/metrics.json
      # This will have browserless delete files older than 30 days in the workspace, checking once a day
      - WORKSPACE_DELETE_EXPIRED=true

  debug-changedetect:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: debug-changedetect
    hostname: debug-changedetect
    user: 1000:1000
    volumes:
      - ./volumes/debug-changedetect/datastore:/datastore
    environment:
      - FETCH_WORKERS=3
      - PORT=5000
      - PUID=1000
      - PGID=1000
      - PLAYWRIGHT_DRIVER_URL=ws://debug-browserless-chrome:3000/
      - METRICS_JSON_PATH=/datastore/metrics.json
    # ports:
      # - 5001:5000
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.debug-changedetect-http.rule=Host(`debug-changedetect.iamon99.com`)'
      - 'traefik.http.routers.debug-changedetect-http.entrypoints=web'
      - 'traefik.http.routers.debug-changedetect-http.middlewares=debug-changedetect-https'
      - 'traefik.http.middlewares.debug-changedetect-https.redirectscheme.scheme=https'
      - 'traefik.http.routers.debug-changedetect.rule=Host(`debug-changedetect.iamon99.com`)'
      - 'traefik.http.routers.debug-changedetect.entrypoints=websecure'
      - 'traefik.http.routers.debug-changedetect.tls.certresolver=myresolver'
      - 'traefik.http.services.debug-changedetect.loadbalancer.server.port=5000'

networks:
  default:
    external:
      name: traefik-proxy-network
