# https://docs.browserless.io/docs/docker.html#function-incognito-mode

services:
  changedetect-playwright-chrome:
    container_name: changedetect-playwright-chrome
    hostname: changedetect-playwright-chrome
    image: browserless/chrome
    restart: always
    shm_size: 2gb
    volumes:
      - /dev/shm/changedetect-playwright-chrome:/dev/shm
    ports:
      - 15999:3000

      
    environment:
      - EXIT_ON_HEALTH_FAILURE=true
      # means how many client can connect to this browserless machine
      - MAX_CONCURRENT_SESSIONS=10
      - MAX_QUEUE_LENGTH=99999
      - CONNECTION_TIMEOUT=30000
      - DEFAULT_IGNORE_HTTPS_ERRORS=true
      - ENABLE_CORS=true
      - PREBOOT_CHROME=true
      - KEEP_ALIVE=true
      - ENABLE_API_GET=true
      - DEFAULT_LAUNCH_ARGS=["--window-size=1920,5080"]
      - FUNCTION_ENABLE_INCOGNITO_MODE=true
      - METRICS_JSON_PATH=/root/metrics.json
      # This will have browserless delete files older than 30 days in the workspace, checking once a day
      - WORKSPACE_DELETE_EXPIRED=true

networks:
  default:
    external:
      name: traefik-proxy-network
