version: "3.9"
services:
  checkmk:
    image: checkmk/check-mk-raw:2.0.0-latest
    ports:
      - "8089:5000"
    volumes:
      - ./volumes/omd/sites:/omd/sites
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: "Asia/Hong_Kong"
    tmpfs:
      - /opt/omd/sites/cmk/tmp:uid=1000,gid=1000
    restart: unless-stopped
    ulimits:
      nofile: 1024
