version: "2"
services:
  mongodb:
    image: docker.io/bitnami/mongodb:4.2
    volumes:
      - "mongodb_data:/bitnami/mongodb"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_USERNAME=admin
      - MONGODB_DATABASE=bitnami_parse
      - MONGODB_PASSWORD=admin
  parse:
    image: docker.io/bitnami/parse:4
    ports:
      - "1339:1337"
    volumes:
      - "parse_data:/bitnami/parse"
    depends_on:
      - mongodb
    environment:
      - PARSE_HOST=127.0.0.1
      - PARSE_DATABASE_HOST=mongodb
      - PARSE_DATABASE_PORT_NUMBER=27017
      - PARSE_DATABASE_USER=admin
      - PARSE_DATABASE_NAME=bitnami_parse
      - PARSE_DATABASE_PASSWORD=admin
  parse-dashboard:
    image: docker.io/bitnami/parse-dashboard:3
    ports:
      - "4040:4040"
    volumes:
      - "parse_dashboard_data:/bitnami"
    depends_on:
      - parse

    # https://github.com/bitnami/bitnami-docker-parse-dashboard#environment-variables
    # PARSE_DASHBOARD_ENABLE_HTTPS: Whether to enable HTTPS for Parse Dashboard by default. Default: no
    # PARSE_DASHBOARD_EXTERNAL_HTTP_PORT_NUMBER: External HTTP port for Parse Dashboard. Default: 80
    # PARSE_DASHBOARD_EXTERNAL_HTTPS_PORT_NUMBER: External HTTPS port for Parse Dashboard. Default: 80
    # PARSE_DASHBOARD_PARSE_HOST: Parse server host. Default: parse
    # PARSE_DASHBOARD_PORT_NUMBER: Port number in which Parse Dashboard will run. Default: 4040
    # PARSE_DASHBOARD_PARSE_PORT_NUMBER: Parse server port number. Default: 1337
    # PARSE_DASHBOARD_PARSE_APP_ID: Parse app ID. Default: myappID
    # PARSE_DASHBOARD_PARSE_APP_NAME: Parse app name. Default: myappID
    # PARSE_DASHBOARD_PARSE_MASTER_KEY: Parse master key: mymasterKey
    # PARSE_DASHBOARD_PARSE_MOUNT_PATH: Parse server mount path. Default: /parse
    # PARSE_DASHBOARD_PARSE_PROTOCOL: Parse server protocol. Default: https
    # PARSE_DASHBOARD_USERNAME: Parse Dashboard user name. Default: user
    # PARSE_DASHBOARD_PASSWORD: Parse Dashboard password. Default: bitnami

    environment:
      - PARSE_HOST=127.0.0.1

volumes:
  mongodb_data:
    driver: local
  parse_data:
    driver: local
  parse_dashboard_data:
    driver: local
