version: "3"
services:
  react_host:
    build:
      context: ./react_host
      dockerfile: dockerfile
    volumes:
      - "./react_host/App:/App"
    ports:
      - "3002:3000"
    command: "/App/scripts/build.sh"

  tests_host:
    build:
      context: ./tests_host
      dockerfile: dockerfile
    volumes:
      - "./tests_host/integration-tests:/integration-tests"
      - "./tests_host/screenshots:/screenshots"
    command: "wait-for-it.sh react_host:3000 -- mocha --recursive /integration-tests"
    depends_on:
      - react_host
