version: "3.8"

services:
  homeassistant:
    image: homeassistant/home-assistant:latest
    restart: unless-stopped
    privileged: true
    volumes:
      - ./volumes/homeassistant:/config
    ports:
      - 8123:8123

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Hong_Kong
      - VERSION=docker
    # labels:
    #   traefik.enable: "true"
    #   traefik.docker.network: web
    #   traefik.http.routers.homeassistant.rule: Host(`home-cluster.${CF_DOMAIN}`)
    #   traefik.http.routers.homeassistant.entrypoints: https
    #   traefik.http.routers.homeassistant.tls.certresolver: cloudflare
    #   traefik.http.services.homeassistant.loadbalancer.server.port: 8123

    #   traefik.tcp.routers.homekit.entrypoints: homekit
    #   traefik.tcp.routers.homekit.service: homeassistant
    #   traefik.tcp.services.homeassistant.loadbalancer.server.port: 21064

    # traefik.udp.routers.homekitudp.entrypoints: homekitudp
    # traefik.udp.routers.homekitudp.service: homeassistant
    # traefik.udp.services.homeassistant.loadbalancer.server.port: 5353
