FROM ubuntu:latest

ENV DEBIAN_FRONTEND noninteractive

RUN apt update &&\
    apt install  openssh-server sudo -y &&\
    apt install openjdk-8-jdk -y &&\
    apt install git wget curl -y


# build specific tools starts here

RUN curl -sL https://deb.nodesource.com/setup_14.x | sudo bash - 
RUN apt -y install nodejs
RUN node  -v

RUN apt -y install gcc g++ make

RUN curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
RUN apt update && sudo apt install yarn
RUN yarn -V

# build specific tools end here

RUN service ssh start
EXPOSE 22

# expose port for react app
EXPOSE 3000

CMD ["/usr/sbin/sshd","-D"]

