version: "3"
services:
  healthchecks:
    image: lscr.io/linuxserver/healthchecks:latest
    container_name: healthchecks
    environment:
      - PUID=1000
      - PGID=1000
      - SITE_ROOT=http://healthcheck.iamon99.com
      - SITE_NAME=louislabs
      - DEFAULT_FROM_EMAIL=healthcheck@louislabs.com
      # - EMAIL_HOST=localhost
      # - EMAIL_PORT=25
      # - EMAIL_HOST_USER=redacted
      # - EMAIL_HOST_PASSWORD=redacted
      # - EMAIL_USE_TLS=True
      - ALLOWED_HOSTS=["*"]
      - SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
    volumes:
      - ./volumes/data:/config
    ports:
      - 8097:8000
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.healthcheck-http.rule=Host(`healthcheck.iamon99.com`)"
      - "traefik.http.routers.healthcheck-http.entrypoints=web"
      - "traefik.http.routers.healthcheck-http.middlewares=healthcheck-https"
      
      - "traefik.http.middlewares.healthcheck-https.redirectscheme.scheme=https"
      - "traefik.http.routers.healthcheck.rule=Host(`healthcheck.iamon99.com`)"
      - "traefik.http.routers.healthcheck.entrypoints=websecure"
      - "traefik.http.routers.healthcheck.tls.certresolver=myresolver"
      - "traefik.http.services.healthcheck.loadbalancer.server.port=8000"

networks:
  default:
    external:
      name: traefik-proxy-network
