services:
  healthchecks:
    image: lscr.io/linuxserver/healthchecks:latest
    container_name: healthchecks
    environment:
      - PUID=1000
      - PGID=1000
      - SITE_ROOT=http://healthcheck.iamon99.com
      - SITE_NAME=louislabs
      - DEFAULT_FROM_EMAIL=healthcheck@louislabs.com

      - ALLOWED_HOSTS=["*"]
      - SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
      # - EMAIL_HOST=localhost
      # - EMAIL_PORT=25
      # - EMAIL_HOST_USER=redacted
      # - EMAIL_HOST_PASSWORD=redacted
      # - EMAIL_USE_TLS=True

    volumes:
      - ./volumes/data:/config
    
    ports:
      - 8097:8000
    
    restart: unless-stopped

    labels:
      # # TODO: 2023-Jul-12, remove me as no encrypted traffic between cloudflare and my server anymore.
      # - "traefik.enable=true"
      # - "traefik.http.routers.healthcheck-http.rule=Host(`healthcheck.iamon99.com`)"
      # - "traefik.http.routers.healthcheck-http.entrypoints=web"
      # - "traefik.http.routers.healthcheck-http.middlewares=healthcheck-https"
      
      # - "traefik.http.middlewares.healthcheck-https.redirectscheme.scheme=https"
      # - "traefik.http.routers.healthcheck.rule=Host(`healthcheck.iamon99.com`)"
      # - "traefik.http.routers.healthcheck.entrypoints=websecure"
      # - "traefik.http.routers.healthcheck.tls.certresolver=myresolver"
      # - "traefik.http.services.healthcheck.loadbalancer.server.port=8000"


      - "traefik.enable=true"

      - "traefik.http.routers.healthcheck-iamon99-http.rule=Host(`healthcheck.iamon99.com`)"
      - "traefik.http.routers.healthcheck-iamon99-http.entrypoints=web"

      # NOTE: container serving 3001 port
      - "traefik.http.services.healthcheck-iamon99-http.loadbalancer.server.port=8000"



networks:
  default:
    name: traefik-proxy-network
    external: true
