version: "3"
services:
  healthchecks:
    image: lscr.io/linuxserver/healthchecks:latest
    container_name: healthchecks
    environment:
      - PUID=1000
      - PGID=1000
      - SITE_ROOT=http://192.168.10.61:8084
      - SITE_NAME=louislabs
      - DEFAULT_FROM_EMAIL=healthcheck@louislabs.com
      # - EMAIL_HOST=localhost
      # - EMAIL_PORT=25
      # - EMAIL_HOST_USER=redacted
      # - EMAIL_HOST_PASSWORD=redacted
      # - EMAIL_USE_TLS=True
      - ALLOWED_HOSTS=["*"]
      - SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
    volumes:
      - ./volumes/data:/config
    ports:
      - 8084:8000
    restart: unless-stopped
